### ISSUE TITLE
Hardwired Mining Laser hullmod "built-in" weapons not removed from inventory when replaced by other weapons

### ISSUE THREAD

**Issue by Faryaa** [RkShaRkz/Starsector-IntelliJ-Template#35]
When swapping LR mining lasers/mining lances around or with a different small energy weapon these quasi-built-in weapons are supposed to be deleted from your inventory as they are designed to be incompatible with any other ship (and they even have a 0 credit cost). This worked as intended in original mod, but does not seem to be a thing here anymore. 
Affected ships : Prospector, Pathfinder, Bear, Groundhog, Rockhound etc.

**Comment by RkShaRkz** [comment]
Deleted that "feature" on purpose, because iterating through whole inventory and deleting few weapons if found does not really warrant a check happening on every frame in my book. Especially if/when your inventory grows to be rather large.

The so called 'immersion' benefit does not outweight the performance cost so it's not going to be put back in it's original form.

Even [this bit](https://github.com/RkShaRkz/Starsector-IntelliJ-Template/blob/vayra-merged-mod/src/data/scripts/hullmods/VayraMiningTools.java#L53-L63) isn't really flying cool with me.

The `VayraInventoryStripper` OnEveryFramePlugin was simply nuked out of existence.

I'm sorry if this is a dealbreaker for you, but spending *any* amount of CPU time on removing useless no-cost weapons is just not something that's going to make a comeback. While it may be fluff and flavor, it's also a non-insignificant time waste with inventories of over 50k.

However, if you really do want it back - here, i'll help you out.

**data/scripts/VayraInventoryStripper.java**
```
package data.scripts;

import com.fs.starfarer.api.EveryFrameScript;
import com.fs.starfarer.api.Global;
import com.fs.starfarer.api.campaign.CampaignFleetAPI;
import com.fs.starfarer.api.campaign.CargoAPI;
import com.fs.starfarer.api.campaign.SectorAPI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class VayraInventoryStripper implements EveryFrameScript {

    public static final List<String> WEAPON_IDS = new ArrayList<>(Arrays.asList(
            "vayra_lr_mining_laser",
            "vayra_mining_lance",
            "vayra_looted_tpc"));

    public VayraInventoryStripper() {
    }

    @Override
    public void advance(float amount) {
        SectorAPI sector = Global.getSector();
        if (!sector.isPaused()) {
            // should help with script weight if we only do shit while paused, since most stuff only does shit when unpaused
            return;
        }

        CampaignFleetAPI playerFleet = Global.getSector().getPlayerFleet();
        if (playerFleet != null) {
            List<CargoAPI> cargos = new ArrayList<>();
            if (sector.getPlayerFleet().getCargo() != null) {
                cargos.add(sector.getPlayerFleet().getCargo());
            }
            if (sector.getPlayerFleet().getInteractionTarget() != null && sector.getPlayerFleet().getInteractionTarget().getCargo() != null) {
                cargos.add(sector.getPlayerFleet().getInteractionTarget().getCargo());
            }

            for (String weaponId : WEAPON_IDS) {
                for (CargoAPI c : cargos) {
                    while (c.getNumWeapons(weaponId) > 0) {
                        c.removeWeapons(weaponId, 1);
                    }
                }
            }
        }

    }

    @Override
    public boolean isDone() {
        return false;
    }

    @Override
    public boolean runWhilePaused() {
        return true;
    }
}
```

**ModPlugin**
```
     @Override
    public void onNewGameAfterTimePass() {

        log.info("new game started, adding scripts");
        Global.getSector().addScript(new VayraInventoryStripper());
    }
```

just add the VayraInventoryStripper to the mod plugin's `onNewGameAfterTimePass()` method and there you go. you keep that feature, and I don't. simple as that.

**Comment by RkShaRkz** [comment]
Like, even if I'm wrong and it's actually *not* slowing down the game as much as I think I remember it - the benefit simply doesn't outweight the cost. The instructions on how to bring it back are here.

As far as I'm concerned, this issue is as good as "closing -> won't fix -> non issue".

CC @Faryaa

**Comment by Faryaa** [comment]
Why not removing the hullmod completely then? Just make ships use permanently attached mining lances, but buff their range as well. So ships have unique decent pd that you can't replace. Because cluttering the inventory with weapons you can't use in any way is not a good solution either.

**Comment by RkShaRkz** [comment]
@Faryaa well, I didn't remove the hullmod for the initial version because I didn't really want to deal with it as I was more interested in fixing bugs and problems and not dealing with "rebalancing". But removing the hullmod at *any point now or in the future* will make it incompatible with previous saves. Just to be on the same page, we're talking about the `VayraMiningTools` hullmod.

Besides, the hullmod isn't technically *completely* broken, only the part where it iterates through your whole inventory to delete `vayra_lr_mining_laser` and `vayra_mining_lance` is removed. It will still fill up open slots with them if you have unused OP. The false constraint of them not working anywhere else is lifted. Are they both not small energy point defense weapons?

So, inconvenienced people will just have to sell off the clutter for 0 credits and move on, or try to make a problem out of something that's not really that much of a problem.

It's similar to how the original mod made you choose between Vayra bounty manager (which offers high value bounties) or Magic bounties but couldn't use both, and this one *can* use both, it's just that when both are used some bounties can be/are duplicated. But they both go away from their respective lists when you complete them.

The problem is purely cosmetic, i'd even go as far as to say "only visual" - but if you're really bent on having it behave as it did before - it's open source, i cant stop you from forking your own copy and reviving the VayraInventoryStripper and putting it back to where it belongs to have it function just like in the original.

I'm just not that big of a fan of "quasi this" and "quasi that". "blablabla here are these two energy PD weapons you can't buy, can't salvage, and can't own, yet they just spawn out of the blue in empty weapon slots but when you put anything in those slots the weapons disappear into thin air where they came from". Sounds a bit silly when it's put like that, doesn't it.

The prospector and the other ships could have had them be *actually* built-in in their `.ship` files, but no, it went with the hullmod workaround approach which saps on perfomance, and left the slots remain "free real estate". There was probably a reason why it was done that way, no? The weapons can be used just fine everywhere else, they can't be salvaged, they can be sold fine so cluttering isn't really that much of a problem, is it?

For some reason, vayra decided to not have these 4 ships use builtin free PDs you can't obtain anywhere else but have quasi-builtin weapons that quasi-don't work on any other ship that are looked for/removed from your inventory in every single frame of the game even if you don't have the ships or any instances of those weapons in your inventories.
