### ISSUE TITLE
[Crash] Ship system vayra_exemplardrones overwriting vanilla drone_pd.system file

### ISSUE THREAD

**Issue by Tick-Tock-Man** [RkShaRkz/Starsector-IntelliJ-Template#74]
The issue title is probably self-explanatory, Shipsystem vayra_exemplardrones is using a vanilla drone_pd.system file but with changed system ID, causing other MODs that still use the vanilla PD Drone Shipsystem to instant crash, since they will not be able to find ID drone_pd due to it being overwritten. 

The crash can be reproduced by using any MOD ships/wings that still uses PD Drone in combat, the game will crash when the specific ship/wing is attempting to use its system. The game can also crash when attempting to hover the cursor over these ships/wings when in fleet/weapon menu.

```
ERROR com.fs.starfarer.combat.CombatMain  - java.lang.RuntimeException: System with id [drone_pd] not found
java.lang.RuntimeException: System with id [drone_pd] not found
	at com.fs.starfarer.combat.entities.Ship.<init>(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.loading.specs.oooo.super(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.campaign.fleet.FleetMember.instantiateForCombat(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.combat.CombatFleetManager.super(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.combat.CombatFleetManager.Ò00000(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.combat.CombatFleetManager.deploy(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.combat.ai.admiral.oOoO.if.super(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.combat.ai.admiral.oOoO.Òo0000(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.combat.ai.admiral.oOoO.Õo0000(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.combat.ai.admiral.BaseBattleStrategy.super(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.combat.ai.admiral.AdmiralAI.advance(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.combat.CombatFleetManager.advance(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.combat.CombatEngine.advanceInner(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.combat.CombatEngine.advance(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.combat.CombatState.traverse(Unknown Source) ~[port_obf.jar:?]
	at com.fs.state.AppDriver.begin(Unknown Source) ~[port.common_obf.jar:?]
	at com.fs.starfarer.combat.CombatMain.main(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.StarfarerLauncher.super(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source) ~[port_obf.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1575) [?:?]
```

**Comment by RkShaRkz** [comment]
@Tick-Tock-Man appreciate the bugreport, but I'd have preferred some clearer test-steps that I can just run through.

**Comment by RkShaRkz** [comment]
While there seems to be a few more changes than just the system ID change, yes, it's a big let-through and another lazy/suboptimal approach to this issue. Will be changed and merged-in shortly.

**Comment by RkShaRkz** [comment]
Sorry, confirmed to be a non-issue as vayra isn't causing it. While I understand your concern and that *yes*, vayra was using drone_pd.system which was probably clobbering the vanilla drone_pd.system, renaming that system still doesn't resolve the issue even when file clobbering no longer happens. The issue remains even with the fix done in the open PR referencing this issue.

**Comment by RkShaRkz** [comment]
Zero uses of this `drone_pd` ship system found in vanilla as well.

**Comment by RkShaRkz** [comment]
@Tick-Tock-Man please provide exact test steps. **exact and repeatable**, with enough clarification in them without being ambiguous like "use any ship that has this ship system" since, well, tough luck, I can't find any in my modset or vanilla. And trying to give that ship system to any vayra ships somehow turns them into LPCs and those crash with the exact same stacktrace you posted.

**Comment by RkShaRkz** [comment]
hold on, my test criteria/sample was all bad. i'm gonna take another jab at this.

**Comment by RkShaRkz** [comment]
Merged-in in commit [c1e9a3b](https://github.com/RkShaRkz/Starsector-IntelliJ-Template/commit/c1e9a3b0e45314579421cbfdd929cc3b268d8a93)

**Comment by RkShaRkz** [comment]
@Tick-Tock-Man since you're having this crash and are probably blocked, but I don't want to release a new version with just this minor fix, do you want me to upload you a pre-release version to unblock you so you can keep on playing your game?

**Comment by Tick-Tock-Man** [comment]
Thanks for the research and I'm sorry if I cause any non-issue trouble! 

What makes me think that it could be an overwriting issue is that, there was a similar case on fossic.org (the Chinese Starsector Community) where the player crashes in the Hypershunt Tesseract fight due to his temporalshell.system being overwritten by a Chinasector MOD. This MOD is using a new temporalshell.system file with a different system ID: [https://www.fossic.org/thread-12994-1-1.html](url). 

When I got drone_pd crash myself, I tried to search this filename in my MOD folder and realized that Vayra is the only one that is using vanilla system filename so I think it is suspicious. 

I did another test after I saw your instructions, and I will try to provide the details clearer, but I have to apologize for bad English in advance. What I did in the new test: 
1. I have a clean 0.97a-rc11 MOD environment with only Lib MODs, VayraMerged and this MOD called MFGA: https://www.fossic.org/forum.php?mod=viewthread&tid=12320&highlight=%E5%B0%8F%E9%A3%9E%E6%9C%BA, a mod from fossic that has one of its wings using the drone_pd system. 
![QQ20241210-095711](https://github.com/user-attachments/assets/6b0420fa-ce44-4fbd-854d-46a7eaefd7b4)
2. I tried with only MFGA on and I get the wing in the attached pic, when I hover my cursor on it in the wings selection menu, it shows the vanilla drone_pd system and did not crash. 
3. I tried with MFGA and Vayra enabled at the same time and hover my cursor again, it crashed. 
4. I understand that drone_pd is an abandoned system (probably from 0.91 or some versions later) so it will be a bit harder to get in vanilla, so I tried to change vanilla Buffalo's system to drone_pd, and it crashes in codex when I click it. 
5. I tried to rename the drone_pd.system file in Vayra folder to vayra_exemplardrones.system and do the same things again, it did not crash.

**Comment by Tick-Tock-Man** [comment]
Sorry I misclicked the reopen issue, I think I can actually deal with the problem by changing the filename on my side. Since there are not many MODs that still uses drone_pd, I do not think this problem is worth fixing on your side or make a new version just because of it, as you just said! 

Edit: I will try to change the filename on my side for now and wait for the new version of Vayra which may include this fix alongside with others, this should do.

**Comment by RkShaRkz** [comment]
well, i had a hardtime confirming the issue at first, then I had a "hard time resolving" the issue, but mainly because the "ships" i tried testing with were actually fighter wings.... :D 

but once I broke an existing ship to test out changes in and out of combat, here are the pictures; ignore the heavy_drone_tether using a different system, that didn't get merged-in, that's just for my testing purposes.

# screenshots

## ship with exemplar PD drones system (vayra's clobbered drone_pd system)
![screenshot004](https://github.com/user-attachments/assets/f273501d-64c6-4708-b106-987efe117d86)

## ship with original drone_pd system
![screenshot005](https://github.com/user-attachments/assets/1fc74388-71e9-4dde-8a21-c9d01018605d)

## in combat 1
![screenshot008](https://github.com/user-attachments/assets/81d1898a-85db-487f-850c-d65f68f6428b)

## in combat 2 (notice the 3 drones deployed thing)
![screenshot010](https://github.com/user-attachments/assets/4f43dafb-6cca-4d58-a9d8-78996f6aed79)

**Comment by Tick-Tock-Man** [comment]
Thanks for the efforts! And sorry for giving ambiguous reports which may waste your time. Will definitely try to provide clearer reports next time.

**Comment by RkShaRkz** [comment]
> Thanks for the efforts! And sorry for giving ambiguous reports which may waste your time. Will definitely try to provide clearer reports next time.

no problem man, just remember. the less time i have to spend to pin down the repro-steps (and the scenario I have to perform to get to the crash/broken part) which i can then perform exactly after fixing it to verify that the issue is resolved, the better for both of us.

for the time being, just take a look at the PR i merged in, do the same thing, and call it a day. try not to rename it to something else because if you end up with two different files for the same system, some other problems might arise :D (will happen if you just drag and drop from zip to folder)

also, thanks for reporting it and, well, helping me fix it :)
